export const Routes = {
  Splash: 'splash',
  Login: 'login',
  Home: 'home',
  SelectCategory: 'selectCategory',
  ProductSuccess: 'productSucess',
  UpdateProduct: 'updateProduct',
  Suggestions: 'suggestions',
  Orderlist: 'orderlist',
  CreateProduct: 'createProduct',
  Rejected: 'rejected',
  HomeTab: 'hometab',
  CategoriesTab: 'categoriestab',
  transactions: 'transactions',
  orderDetail: 'orderDetail',
  UsersTab: 'userstab',
  AdminTab: 'adminTab',
  Privacy_Policy: 'privacy',
};
